[package]
name = "midicrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.2.6", features = ["color", "suggestions", "wrap_help", "derive"]}
midir = "0.8.0"
